---
# tasks file for apache
- name: "apache installation"
  apt:
    name: "apache2"
    state: "present"

- name: "apache service activation"
  service:
    name: "apache2"
    state: "started"
    enabled: yes

- name: "install php packages"
  include_tasks: "php-install.yml"
  when: php_install|default(False)|bool
