---

mediawiki_db_name: "mediawiki"

mediawiki_db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32393163386162396334626362643335373535346534613539616637666538643465363364613132
          3238656437333139343035363930313630366235393232630a633261636566323663373566303534
          63386264643931376366333839306262393738386265373439633939356264633738656164666136
          6338326132373736320a376432366663376664373739313463353239363135643663393532646334
          3735

mediawiki_admin_user: "admin"

mediawiki_admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30323834633433346164303435666439393530373061613662633432323436333161626133356633
          6530373838393735303661626531353362393462653464620a306330633061653136343939643465
          31353335356666386630656538653938363230323633663561666232316237646539366532326332
          3764633530333061370a633461353738356233396433623561656361346530373733643037616363
          6137

mediawiki_name: "mediawiki"

mediawiki_title: "Un media wiki random"

mediawiki_directory: "/var/www/html/{{mediawiki_name}}"

mediawiki_maintenance_directory: "{{mediawiki_directory}}/maintenance"

mediawiki_db_hosts: "{{groups.db.0}}"

mediawiki_archive_url: "https://releases.wikimedia.org/mediawiki/1.37/mediawiki-1.37.1.tar.gz"
